package probs

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million (4,000,000),
find the sum of the even-valued terms.

*/

func Prob2() int64 {

	var sum int64 = 0
	var limit int64 = 4000000

	var a, b, h int64 = 1, 1, 0
	h = a + b

	for h < limit {
		/*if b%2 == 0 {
			sum = sum + b
		}*/
		sum = sum + h
		a = b + h
		b = h + a
		h = a + b
	}
	return sum
}
