package probs

/*

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

start from 7th triangle
calculate following 8th triangle from formula : n(n+1)/2
*/

func Prob12() uint {

	var divlist = []uint{0}

	var i uint = 0
	var tri uint = 0

	for len(divlist) < 501 {
		i++
		tri = tri + i

		var div uint = 0
		var index uint = 1

		for index*index < tri {
			if tri%index == 0 {
				div = div + 2
			}
			index++
		}

		if index*index == tri {
			div++
		}

		for len(divlist) <= int(div) {
			divlist = append(divlist, tri)
		}
	}

	return divlist[500+1]
}
